import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {git,snapshot,commitSelected,publish,summarizeChecks,pullRequestStatus} from '../delivery.mjs';
async function repo(){const dir=await mkdtemp(join(tmpdir(),'lew-git-'));await git(dir,['init','-b','main']);await git(dir,['config','user.name','lew test']);await git(dir,['config','user.email','lew@example.test']);await writeFile(join(dir,'tracked.txt'),'first');await git(dir,['add','.']);await git(dir,['commit','-m','initial']);await git(dir,['checkout','-b','lew/task']);return dir;}
test('selected commit preserves unrelated staged changes and includes new files',async()=>{const dir=await repo();try{await writeFile(join(dir,'tracked.txt'),'modified');await git(dir,['add','tracked.txt']);await writeFile(join(dir,'new.txt'),'new');const current=await snapshot(dir);await commitSelected(dir,{fingerprint:current.fingerprint,files:['new.txt'],message:'add new'},'lew/task');assert.equal((await git(dir,['show','HEAD:tracked.txt'])),'first');assert.equal((await git(dir,['show','HEAD:new.txt'])),'new');assert.equal((await git(dir,['diff','--cached','--name-only'])).trim(),'tracked.txt');}finally{await rm(dir,{recursive:true,force:true});}});
test('stale review is rejected when an untracked file changes',async()=>{const dir=await repo();try{await writeFile(join(dir,'new.txt'),'first');const current=await snapshot(dir);await writeFile(join(dir,'new.txt'),'changed');await assert.rejects(commitSelected(dir,{fingerprint:current.fingerprint,files:['new.txt'],message:'commit'},'lew/task'),/changé/);}finally{await rm(dir,{recursive:true,force:true});}});
test('unknown paths and .env files cannot be silently added',async()=>{const dir=await repo();try{await writeFile(join(dir,'.env'),'private');const current=await snapshot(dir);assert.equal(current.files.find(f=>f.path==='.env').selectable,false);await assert.rejects(commitSelected(dir,{fingerprint:current.fingerprint,files:['../outside'],message:'commit'},'lew/task'),/invalide/);}finally{await rm(dir,{recursive:true,force:true});}});
test('publishing retries push safely and reuse the existing pull request',async()=>{const dir=await repo(),remote=await mkdtemp(join(tmpdir(),'lew-remote-'));try{await git(remote,['init','--bare']);await git(dir,['remote','add','origin',remote]);let count=0,created=null;const request=async(repo,path,options)=>{if(path.startsWith('pulls?'))return created?[created]:[];count++;assert.equal(options.body.head,'lew/task');created={number:7,html_url:'https://github.com/example/repo/pull/7'};return created;};const head=(await git(dir,['rev-parse','HEAD'])).trim();const input={title:'A task',body:'Details',base:'main',head};await publish(dir,'example/repo','lew/task',input,request);const second=await publish(dir,'example/repo','lew/task',input,request);assert.equal(second.existing,true);assert.equal(count,1);assert.equal((await git(remote,['rev-parse','refs/heads/lew/task'])).trim(),head);}finally{await rm(dir,{recursive:true,force:true});await rm(remote,{recursive:true,force:true});}});
test('CI combines status contexts, failed checks and partial permissions without false success',async()=>{assert.equal(summarizeChecks({},{}).state,'none');assert.equal(summarizeChecks({check_runs:[{name:'test',status:'completed',conclusion:'success'}]},{statuses:[{context:'preview',state:'pending'}]}).state,'pending');assert.equal(summarizeChecks({check_runs:[{name:'test',status:'completed',conclusion:'failure'}]},{}).state,'failure');const result=await pullRequestStatus('example/repo','lew/task',async(repo,path)=>{if(path.startsWith('pulls'))return [{number:3,title:'task',head:{sha:'abc'},base:{ref:'main'},state:'closed',merged_at:'today'}];throw new Error('Access denied');});assert.equal(result.pr.state,'merged');assert.equal(result.checks.incomplete,true);});
