export const planSchema={type:'object',properties:{summary:{type:'string'},tasks:{type:'array',items:{type:'object',properties:{id:{type:'string'},title:{type:'string'},instructions:{type:'string'},dependsOn:{type:'array',items:{type:'string'}},expectedResult:{type:'string'}},required:['id','title','instructions','dependsOn','expectedResult'],additionalProperties:false}}},required:['summary','tasks'],additionalProperties:false};
export const resultSchema={type:'object',properties:{summary:{type:'string'},verdict:{type:'string',enum:['pass','changes_required','blocked']},findings:{type:'array',items:{type:'string'}},tests:{type:'array',items:{type:'string'}},unresolved:{type:'array',items:{type:'string'}}},required:['summary','verdict','findings','tests','unresolved'],additionalProperties:false};
export function validatePlan(plan){
  if(!plan||typeof plan.summary!=='string'||plan.summary.length>4000||!Array.isArray(plan.tasks)||!plan.tasks.length||plan.tasks.length>12)throw new Error('Plan invalide : 1 à 12 tâches attendues.');
  const ids=new Set();for(const t of plan.tasks){if(!/^[a-z][a-z0-9-]{0,39}$/.test(t.id)||ids.has(t.id))throw new Error('Identifiant de tâche invalide ou dupliqué.');ids.add(t.id);for(const k of ['title','instructions','expectedResult'])if(typeof t[k]!=='string'||!t[k].trim()||t[k].length>10000)throw new Error('Tâche incomplète.');if(!Array.isArray(t.dependsOn)||new Set(t.dependsOn).size!==t.dependsOn.length)throw new Error('Dépendances invalides.');}
  // A single Git lineage makes every dependent base explicit. Parallel multi-parent merges are deliberately unsupported.
  for(let i=0;i<plan.tasks.length;i++){const t=plan.tasks[i];if(t.dependsOn.length>1||t.dependsOn.some(d=>!ids.has(d)||d===t.id))throw new Error('Une tâche accepte au maximum un parent Git explicite.');if(i>0&&(t.dependsOn.length!==1||t.dependsOn[0]!==plan.tasks[i-1].id))throw new Error('Cette version exécute une chaîne séquentielle : chaque tâche dépend de la précédente.');if(i===0&&t.dependsOn.length)throw new Error('La première tâche ne doit pas avoir de dépendance.');}
  return structuredClone(plan);
}
export function limits(input={}){const result={concurrency:1,attempts:2,correctionRounds:2,durationMinutes:60,...input};for(const [k,min,max] of [['concurrency',1,1],['attempts',1,5],['correctionRounds',0,5],['durationMinutes',1,240]])if(!Number.isInteger(result[k])||result[k]<min||result[k]>max)throw new Error(`Limite invalide : ${k}.`);return result;}
export function parseResult(text){let result;try{result=JSON.parse(text);}catch{throw new Error('Codex n’a pas fourni le résultat JSON attendu.');}if(typeof result?.summary!=='string'||result.summary.length>20000||!['pass','changes_required','blocked'].includes(result.verdict)||['findings','tests','unresolved'].some(k=>!Array.isArray(result[k])||result[k].length>100||result[k].some(v=>typeof v!=='string'||v.length>10000)))throw new Error('Résultat d’agent invalide.');return result;}
export function nextTask(tasks){return tasks.find(t=>t.status==='pending'&&t.dependsOn.every(d=>tasks.find(p=>p.id===d)?.status==='completed'));}
export function reviewValid(review,snapshot){return !!review&&review.head===snapshot.head&&review.fingerprint===snapshot.fingerprint;}
export function recoverMission(m){const next=structuredClone(m);if(['planning','running','interrupting'].includes(next.status)||(next.status==='paused'&&next.activeWorkspace)){next.status='interrupted';next.activeWorkspace=null;for(const e of next.executions||[])if(e.status==='running'){e.status='error';e.error='Interrompu par redémarrage';}for(const t of next.tasks||[])if(t.status==='running')t.status='interrupted';}return next;}
export function transition(status,action){const map={pause:{running:'paused'},resume:{paused:'running',interrupted:'running',blocked:'running'},interrupt:{running:'interrupting',planning:'interrupting',paused:'interrupting'},cancel:{planning:'cancelled',awaiting_plan:'cancelled',running:'cancelled',paused:'cancelled',interrupted:'cancelled',blocked:'cancelled',ready:'cancelled'}};const next=map[action]?.[status];if(!next)throw new Error('Action incompatible avec l’état actuel.');return next;}
