create table lew.avatars(id uuid primary key, name text not null, definition jsonb not null, created timestamptz not null default now());
create table lew.agents(id uuid primary key, template_key text unique, name text not null, description text not null default '', role text not null, instructions text not null, config jsonb not null, mapping jsonb not null default '{}', avatar_id uuid references lew.avatars(id), active boolean not null default true, updated timestamptz not null default now());
create table lew.missions(id uuid primary key, project_id uuid not null references lew.projects(id), status text not null, data jsonb not null, created timestamptz not null default now(), updated timestamptz not null default now());
create table lew.mission_executions(id uuid primary key, mission_id uuid not null references lew.missions(id), workspace_id uuid not null unique references lew.workspaces(id), data jsonb not null, created timestamptz not null default now());
create table lew.mission_events(id bigint generated always as identity primary key, mission_id uuid not null references lew.missions(id), kind text not null, data jsonb not null, created timestamptz not null default now());
create index lew_missions_project_idx on lew.missions(project_id,created);
create index lew_mission_events_idx on lew.mission_events(mission_id,id);
create index lew_mission_executions_idx on lew.mission_executions(mission_id);
alter table lew.avatars enable row level security;
alter table lew.agents enable row level security;
alter table lew.missions enable row level security;
alter table lew.mission_executions enable row level security;
alter table lew.mission_events enable row level security;
revoke all on lew.avatars, lew.agents, lew.missions, lew.mission_executions, lew.mission_events from public, anon, authenticated;
revoke all on sequence lew.mission_events_id_seq from public, anon, authenticated;
